# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main
pool:
  Default
steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'
- task: UiPathInstallPlatform@3
  inputs:
    cliVersion: 'WIN_22.10.8438.32859'
    cliNupkgPath: '$(Agent.ToolsDirectory)\nupkg\UiPath.CLI.Windows.22.10.8438.32859.zip'
- task: UiPathPack@3
  inputs:
    versionType: 'AutoVersion'
    projectJsonPath: '$(Build.SourcesDirectory)'
    orchestratorConnection: 'Uipath_Testing'
    outputPath: '$(Build.ArtifactStagingDirectory)\Output'
- task: UiPathDeploy@3
  inputs:
    orchestratorConnection: 'Uipath_Testing'
    packagesPath: '$(Build.ArtifactStagingDirectory)\Output'
    folderName: 'Shared'
    entryPoints: 'Main.xaml'
- task: UiPathTest@3
  inputs:
    testTarget: 'TestSet'
    orchestratorConnection: 'Uipath_Testing'
    testSet: 'Coverage_new'
    folderName: 'Modren Example'